name: Deploy Vercel
description: Deploy to Vercel

inputs:
  token:
    description: 'The Vercel token'
    required: true

outputs:
  deploymentUrl:
    description: Vercel
    value: ${{ steps.deploy.outputs.deploymentUrl }}

runs:
  using: 'composite'

  steps:
    # - name: Install Vercel CLI
    #   shell: bash
    #   run: pnpm add -g vercel@33.2.0

    - name: Pull Vercel Environment Information
      shell: bash
      run: npx vercel pull --yes --environment=preview --token=${{ inputs.token }}

    - name: Build Project Artifacts
      shell: bash
      run: npx vercel build --token=${{ inputs.token }}

    - name: Deploy Project Artifacts to Vercel
      shell: bash
      id: deploy
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        npx vercel deploy --prebuilt --token=${{ inputs.token }} > deploy.log
        URL=$(cat deploy.log | grep -o 'https://[^ ]*.vercel.app' | head -n1)
        gh pr comment ${{ github.event.pull_request.number }} -b "Deployed at $URL"
