name: Preview Deploy Vercel
description: Deploy to Vercel Preview

inputs:
  token:
    description: The Vercel token
    required: true
  target:
    description: preview | development
    required: true

runs:
  using: 'composite'

  steps:
    - name: Pull Vercel Environment Information
      shell: bash
      run: npx vercel pull --yes --environment=preview --token=${{ inputs.token }}

    - name: Build Project Artifacts
      shell: bash
      run: npx vercel build --token=${{ inputs.token }}

    - name: Deploy Project Artifacts to Vercel & PR Comment
      if: ${{ inputs.target == 'preview' }}
      id: preview_deploy
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        npx vercel deploy --prebuilt --token=${{ inputs.token }} > deploy.log
        URL=$(cat deploy.log | grep -o 'https://[^ ]*.vercel.app' | head -n1)
        echo "deployed_url=$URL" >> $GITHUB_OUTPUT

    - name: PR Comment Deployed URL
      if: steps.preview_deploy.outputs.deployed_url != ''
      uses: marocchino/sticky-pull-request-comment@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: '${{ inputs.tag }}: ${{ steps.preview_deploy.outputs.deployed_url }}"'

    - name: Deploy Project Artifacts to Vercel
      if: ${{ inputs.target == 'development' }}
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        npx vercel deploy --prebuilt --token=${{ inputs.token }} > deploy.log
