name: Preview Deploy Vercel
description: Deploy to Vercel Preview

inputs:
  token:
    description: The Vercel token
    required: true
  target:
    description: development | production
    required: true

runs:
  using: 'composite'

  steps:
    - name: Pull Vercel Environment Information
      shell: bash
      run: npx vercel pull --yes --environment=preview --token=${{ inputs.token }}

    - name: Build Project Artifacts
      shell: bash
      run: npx vercel build --token=${{ inputs.token }}

    - name: Deploy Project Artifacts to Vercel & PR Comment
      if: ${{ inputs.target == 'preview' }}
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        npx vercel deploy --prebuilt --token=${{ inputs.token }} > deploy.log
        URL=$(cat deploy.log | grep -o 'https://[^ ]*.vercel.app' | head -n1)
        gh pr comment ${{ github.event.pull_request.number }} -b "Deployed at $URL"

    - name: Deploy Project Artifacts to Vercel
      if: ${{ inputs.target == 'development' }}
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        npx vercel deploy --prebuilt --token=${{ inputs.token }} > deploy.log
