name: Production Deploy Vercel
description: Deploy to Vercel Production

inputs:
  token:
    description: 'The Vercel token'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Pull Vercel Environment Information
      shell: bash
      run: npx vercel pull --yes --environment=production --token=${{ inputs.token }}

    - name: Build Project Artifacts
      shell: bash
      run: npx vercel build --prod --token=${{ inputs.token }}

    - name: Deploy Project Artifacts to Vercel(Preview)
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        npx vercel deploy --prebuilt --prod --token=${{ inputs.token }} > deploy.log
        URL=$(cat deploy.log | grep -o 'https://[^ ]*.vercel.app' | head -n1)
        npx vercel alias --token=${{ inputs.token }} set "$URL" yanskun-vercel.vercel.app
