name: Setup Node

inputs:
  working-directory:
    description: 'The working directory to run the command in'
    required: false
    default: '.'

runs:
  using: 'composite'

  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.working-directory }}/package.json
        cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml

    - name: pnpm setup
      uses: pnpm/action-setup@v4
      id: pnpm-install
      with:
        version: 9.0.6
        run_install: false
