name: CI

env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

permissions:
  pull-requests: write

on:
  workflow_dispatch:

  push:

defaults:
  run:
    shell: bash
    working-directory: frontend

jobs:
  preview:
    runs-on: ubuntu-latest
    environment:
      name: preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/actions/setup_node
        with:
          working-directory: frontend

      - name: Deploy Vercel
        uses: ./.github/actions/vercel
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
