name: CI

env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

permissions:
  pull-requests: write

on:
  workflow_dispatch:

  push:

  release:
    types: [published]

defaults:
  run:
    shell: bash
    working-directory: frontend

jobs:
  preview:
    runs-on: ubuntu-latest
    environment:
      name: preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/actions/setup_node
        with:
          working-directory: frontend

      - name: Deploy Vercel(Preview)
        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dvelopment' }}
        uses: ./.github/actions/vercel-preview
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          target: preview

      - name: Deploy Vercel(Development)
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dvelopment' }}
        uses: ./.github/actions/vercel-preview
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          target: development

      - name: Deploy Vercel(Production)
        if: ${{ github.event_name == 'release' }}
        uses: ./.github/actions/vercel-production
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
